# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute .. allels
#'
#' Function GetAlleles description
#'
#' @param Both A character vector vector
#' @param Allele An integer matrix
#' @param n_sample Number of elements
#' @export
GetAlleles <- function(Both, Allele, n_sample) {
    .Call(`_mtAnalysis_GetAlleles`, Both, Allele, n_sample)
}

#' Compute .. frequency values
#'
#' Function GetFreq description
#'
#' @param Freq Frequency matrix
#' @export
GetFreq <- function(Freq) {
    .Call(`_mtAnalysis_GetFreq`, Freq)
}

